### ISSUE TITLE
Where to get Addon which is still compatible with Kodi Krypton?

### ISSUE THREAD

**Issue by M-Reimer** [FernetMenta/pvr.vdr.vnsi#18]
Hello,

with the latest VDR plugin version, it seems to be impossible to connect with Kodi Krypton. At least I failed so far:

15:19:57.145 T:140565316093696   ERROR: AddOnLog: VDR VNSI Client: Login - failed to read greeting from server

Where can I get a Kodi Addon version which works with the latest VDR plugin revision?

**Comment by FernetMenta** [comment]
are you saying https://github.com/FernetMenta/vdr-plugin-vnsiserver/releases/tag/v1.6.0 does not work with Krypton?

**Comment by M-Reimer** [comment]
No, I've tried the latest GIT version. Bad idea?

**Comment by FernetMenta** [comment]
No, just means I missed something on this branch. Should be compatible with Krypton. Could you please post vdr log?

**Comment by M-Reimer** [comment]
Thanks for pointing me to the logs. I forgot that I got a new router and so my IP addresses have changed. I had to add the new address to the "allowed_hosts.conf" file.
Now everything seems to work fine.
