### ISSUE TITLE
VDR no pic

### ISSUE THREAD

**Issue by andiewill** [FernetMenta/pvr.vdr.vnsi#7]
I have an issue with live TV using VDR, it works up to 726 millhouse build then what i get after that and up to date of the latest millhouse test-build is no picture and sound at all, i have traced it back to 726 as stated, ill include my paste-bins if of any use below.

not working
819
https://paste.ubuntu.com/25356527/

working
726
https://paste.ubuntu.com/25357021/

Cheers
andrew

**Comment by FernetMenta** [comment]
sorry, I am not familiar with those builds. I don't observe any issues.

**Comment by andiewill** [comment]
All sorted......After a play around with different settings plugins and advice from the members etc, the thing that worked to get live tv going was to enable the DVB drivers for TBS (CrazyCat) plug in, never used to have to do that before but hey it works with a clean install.

**Comment by FernetMenta** [comment]
great
